package omc.corba.idl;

/**
 * OmcCommunicationOperations.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from omc_communication.idl Montag, 4. Juli 2016
 * 10:36 Uhr MESZ
 */

// As simple as can be omc communication, sending and recieving of strings.
public interface OmcCommunicationOperations {
  String sendExpression(String expr);

  String sendClass(String model);
} // interface OmcCommunicationOperations
