package omc.corba.idl;

/**
 * OmcCommunication.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from omc_communication.idl Montag, 4. Juli 2016 10:36 Uhr MESZ
 */

// As simple as can be omc communication, sending and recieving of strings.
public interface OmcCommunication extends OmcCommunicationOperations,
    org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface OmcCommunication
